language: ruby
gemfile:
- gemfiles/rails_stable.gemfile
- gemfiles/simple_form_latest.gemfile
- gemfiles/rails_latest.gemfile
- gemfiles/mysql.gemfile

rvm:
- 2.1.1
before_install:
- mysql -e 'create database simple_captcha_reloaded_test'
- mysql -e 'create database simple_captcha_reloaded_development'
- psql -c 'create database simple_captcha_reloaded_test' -U postgres
- psql -c 'create database simple_captcha_reloaded_development' -U postgres
- bundle install --jobs=3 --retry=3
- TEMPLATE='spec/template.rb' ENGINE='simple_captcha_reloaded' bundle exec rake dummy:app
- bundle exec rake app:db:test:prepare
script:
- bundle exec rspec
